# --------------Analyze by CIBERSORTx----------------
# Prepred by Xiao Sun, Xueling Li and Min Zhu
# Contact Xueling Li via email: xlli@cmpt.ac.cn or xuelingli16@foxmail.com
# Analyze the csDEP generated by CIBERSORTx

##Step.1 Correct the format of the results of CIBERSORTx and draw heat maps
rm(list = ls())
setwd(".")
library(stringr)
library(pheatmap)

conlabel = "response"                                                           #response
treatlabel = "non"                                                              #non-response

input_path = "./datasets/"
out_path = "./result/"

if (!dir.exists(out_path)) {
  dir.create(out_path)
}

foldername = "GSE119409_cs"
filenames = list.files(paste0(input_path, foldername), pattern = "*_Window24.txt$")

if (length(filenames) > 0) {
  dir.create(paste(out_path, foldername, sep = "", collapse = NULL))
  allfilenames = list.files(paste0(input_path, foldername))
  deletefilenames = allfilenames[!allfilenames %in% filenames]
  for (k in 1:length(deletefilenames)) {
    file.remove(paste0(input_path, foldername, "/", deletefilenames[k]))
  }
  for (k in 1:length(filenames)) {
    tmpname = str_split(filenames[k], '[_]', simplify = T)[, 3]
    tmpname = paste(
      input_path,
      foldername,
      '/',
      foldername,
      "_",
      tmpname,
      '.txt',
      sep = "",
      collapse = NULL
    )
    file.rename(paste0(input_path, foldername, '/', filenames[k]), tmpname)
  }
}

#Draw heat map
filenames = list.files(paste0(input_path, foldername), pattern = "*.txt$")
for (j in 1:length(filenames)) {
  input = paste(input_path,
                foldername,
                '/',
                filenames[j],
                sep = "",
                collapse = NULL)
  outpdf = paste(
    out_path,
    foldername,
    '/',
    str_split(filenames[j], '[.]', simplify = T)[, 1],
    '.pdf',
    sep = "",
    collapse = NULL
  )                             #output file names.
  
  data <-
    read.table(
      input,
      header = T,
      sep = "\t",
      check.names = F,
      row.names = 1
    )
  data = na.omit(data)
  data = data[apply(data, 1, function(x)
    sd(x) != 0),]
  if (nrow(data) > 1) {
    conData = data[, grep(conlabel, colnames(data))]
    treatData = data[, grep(treatlabel, colnames(data))]
    conNum = ncol(conData)
    treatNum = ncol(treatData)
    
    geneName = as.vector(rownames(data))
    dataLength = length(geneName)
    Type = c(rep(conlabel, conNum), rep(treatlabel, treatNum))
    names(Type) = colnames(data)
    Type = as.data.frame(Type)
    pdf(file = outpdf,
        width = 12,
        height = 10)
    pheatmap(
      data,
      annotation = Type,
      color = colorRampPalette(c("blue", "white", "red"))(50),
      cluster_cols = F,
      show_colnames = F,
      scale = "row",
      fontsize = 8,
      fontsize_row = 7,
      fontsize_col = 8
    )
    dev.off()
  }
}

##Step.2 Using t-test to analyze response and non-response groups
rm(list = ls())
library(stringr)

input_path = "./datasets/"
out_path = "./result/"

if (!dir.exists(out_path)) {
  dir.create(out_path)
}

foldername = "GSE119409_cs"
input_path = paste0(input_path, foldername, "/")
out_path = paste0(out_path, foldername, "_ttest/")

if (!dir.exists(out_path)) {
  dir.create(out_path)
}

input_names = list.files(path = input_path, pattern = ".txt$")
filetype = str_split(input_names, '[.]', simplify = T)[, 1]

for (j in 1:length(input_names)) {
  inputfile = paste0(input_path, input_names[j])
  outputfile = paste0(out_path, filetype[j], "_ttest.txt")
  
  data <-
    read.table(
      inputfile,
      header = T,
      sep = "\t",
      check.names = F,
      row.names = 1
    )
  data = as.data.frame(data)
  
  table(is.na(data))
  data = na.omit(data)
  data = data[apply(data, 1, function(x)
    sd(x) != 0),]
  
  conlabel = "response"                                                         #response
  treatlabel = "non"                                                            #non-response
  conData = data[, grep(conlabel, colnames(data))]
  treatData = data[, grep(treatlabel, colnames(data))]
  conNum = ncol(conData)
  treatNum = ncol(treatData)
  
  if (nrow(conData) > 0 && nrow(treatData) > 0) {
    X2 = str_split(colnames(data), '[_]', simplify = T)[, 2]
    contreatlist = data.frame(cbind(colnames(data), X2))
    
    data = t(data)
    avg <- aggregate(data, by = list(contreatlist$X2), FUN = mean)
    var <- aggregate(data, by = list(contreatlist$X2), FUN = var)
    tf <-
      t.test(data[, 1] ~ contreatlist$X2,
             alternative = 't',
             var.equal = F)
    pf <- data.frame(t = "V1",
                     df = "V2",
                     p.value = "V3")
    
    for (k in 1:ncol(data)) {
      tf <-
        t.test(data[, k] ~ contreatlist$X2,
               alternative = 't',
               var.equal = F)
      pf[k,] = c(tf$statistic, tf$parameter, tf$p.value)
      rownames(pf)[k] <- colnames(data)[k]
    }
    avgt = t(avg)
    colnames(avgt) <- paste("Mean", avgt[1,], sep = " ")
    avgt = avgt[-1,]
    result = cbind(pf, avgt)
    vart = t(var)
    colnames(vart) <- paste("Var", vart[1,], sep = " ")
    vart = vart[-1,]
    result = cbind(result, vart)
    outTab = rbind(id = colnames(result), result)
    write.table(
      outTab,
      file = outputfile,
      sep = "\t",
      quote = F,
      col.names = F
    )
  }
}

##Step.3 Merge the results obtained from t-test
rm(list = ls())

library(stringr)
library(dplyr)

input_filepath = "./result/"
out_filepath = "./result/"

foldername = "GSE119409_cs_ttest"

input_path = paste0(input_filepath, foldername, "/")
out_path = paste0(out_filepath, foldername, "/", foldername, "_merge/")

outFile_merge = paste0(out_path, foldername, "_merge.txt")
input_names = list.files(path = input_path, pattern = ".txt$")
celltype = str_split(str_split(input_names, '[_]', simplify = T)[, 3], '[.]', simplify = T)[, 1]

if (!dir.exists(out_path)) {
  dir.create(out_path)
}

allTab_merge = data.frame()
for (j in 1:length(input_names)) {
  data = read.table(
    paste0(input_path, input_names[j]),
    header = T,
    sep = "\t",
    check.names = F
  )
  
  if (nrow(data) > 0) {
    d <- data.frame(Celltype = celltype[j])
    outTab = cbind(d, data)
    if (nrow(allTab_merge) == 0) {
      allTab_merge = outTab
    } else{
      allTab_merge = rbind(allTab_merge, outTab)
    }
  }
}

outTab = rbind(colnames(allTab_merge), allTab_merge)
write.table(
  outTab,
  file = outFile_merge,
  sep = "\t",
  quote = F,
  col.names = F,
  row.names = F
)

##Step.4 Intersect the results obtained from t-test with known protein pathways

rm(list = ls())
library(stringr)
library(dplyr)

input_filepath = "./result/"
out_filepath = "./result/"

foldername = "GSE119409_cs_ttest"

input_path = paste0(input_filepath, foldername, "/")
out_path = paste0(out_filepath, "GSE119409_cs_LR/")

if (!dir.exists(out_path)) {
  dir.create(out_path)
}

out_path_merge = paste0(out_path, "GSE119409_cs_LR_merge/")
if (!dir.exists(out_path_merge)) {
  dir.create(out_path_merge)
}

input_names = list.files(path = input_path, pattern = ".txt$")
filetype = str_split(input_names, '[.]', simplify = T)[, 1]
celltype = str_split(str_split(input_names, '[_]', simplify = T)[, 3], '[.]', simplify =
                       T)[, 1]

reference = read.table("ref.txt",
                       header = T,
                       sep = "\t",
                       check.names = F)
ref_L = reference$Ligand                                                        #ligand
ref_R = reference$Receptor                                                      #receptor
allTab = data.frame()
j = 1

for (i in 1:length(input_names)) {
  outFile = paste0(out_path, filetype[i], "_LR.txt")
  data = read.table(
    paste0(input_path, input_names[i]),
    header = T,
    sep = "\t",
    check.names = F
  )
  d <- data.frame(
    L = "",
    R = "",
    Ligand = "",
    Receptor = ""
  )
  data = cbind(data, d)
  
  list_ref = list()
  list_ref[[1]] = data[, 1]
  list_ref[[2]] = ref_L
  inter_L = Reduce(intersect, list_ref)
  if (length(inter_L) > 0) {
    data[data$id %in% inter_L, "L"] = 1
    for (k in 1:length(inter_L)) {
      R = paste(reference[reference[, "Ligand"] %in% inter_L[k], "Receptor"], collapse = '/')
      data[data$id %in% inter_L[k], "Receptor"] = R
      data[data$id %in% inter_L[k], "Ligand"] = data[data$id %in% inter_L[k], ]$id
    }
  }
  
  list_ref = list()
  list_ref[[1]] = data[, 1]
  list_ref[[2]] = ref_R
  inter_R = Reduce(intersect, list_ref)
  if (length(inter_R) > 0) {
    data[data$id %in% inter_R, "R"] = 1
    for (k in 1:length(inter_R)) {
      L = paste(reference[reference[, "Receptor"] %in% inter_R[k], "Ligand"], collapse = '/')
      data[data$id %in% inter_R[k], "Ligand"] = L
      data[data$id %in% inter_R[k], "Receptor"] = data[data$id %in% inter_R[k], ]$id
    }
  }
  
  data = filter(data, data$L == "1" | data$R == "1")
  if (nrow(data) > 0) {
    d <- data.frame(Celltype = celltype[i])
    outTab = cbind(d, data)
    
    if (j == 1) {
      allTab = outTab
    } else{
      allTab = rbind(allTab, outTab)
    }
    j = j + 1
    
    outTab = rbind(colnames(outTab), outTab)
    write.table(
      outTab,
      file = outFile,
      sep = "\t",
      quote = F,
      col.names = F,
      row.names = F
    )
  }
}

allTab[is.na(allTab)] <-  ""
allTab = rbind(colnames(allTab), allTab)
write.table(
  allTab,
  file = paste0(out_path_merge, "/GSE119409_cs_LR_merge.txt"),
  sep = "\t",
  quote = F,
  col.names = F,
  row.names = F
)




##Step.5 Screening out gene pairs that match ligand receptor
rm(list = ls())
library(stringr)

input_filepath = "./result/GSE119409_cs_LR/GSE119409_cs_LR_merge/"
out_filepath = "./result/GSE119409_cs_LR/GSE119409_cs_LR_merge/"

if (!dir.exists(out_filepath)) {
  dir.create(out_filepath)
}

inputFile = paste0(input_filepath, "GSE119409_cs_LR_merge.txt")
outFile = paste0(out_filepath, "GSE119409_cs_L-R_merge.txt")

data = read.table(inputFile,
                  header = T,
                  sep = "\t",
                  check.names = F)
data[is.na(data)] <-  ""

allTab = data.frame()
for (j in 1:nrow(data)) {
  isL = "Receptor"
  if (data[j, "L"] != 1) {
    isL = "Ligand"
  }
  str = str_split(data[j, isL], '[/]', simplify = T)
  num = length(str)
  rt_Tab = data.frame()
  for (k in 1:num) {
    rt = data[j,]
    rt[1, isL] = str[k]
    if (nrow(rt_Tab) == 0) {
      rt_Tab = rt
    } else{
      rt_Tab = rbind(rt_Tab, rt)
    }
  }
  if (nrow(allTab) == 0) {
    allTab = rt_Tab
  } else{
    allTab = rbind(allTab, rt_Tab)
  }
}

data = allTab

data_Ligand = data[data$L == 1, ]
data_Receptor = data[data$R == 1, ]

data_Ligand$L_R  = paste0(data_Ligand$Ligand, "_", data_Ligand$Receptor)
data_Receptor$L_R = paste0(data_Receptor$Ligand, "_", data_Receptor$Receptor)

intersect(data_Ligand$LR, data_Receptor$L_R)
result = merge(x = data_Ligand, y = data_Receptor, by = "L_R")

result = result[(result$p.value.x < 0.05), ]
result = result[(result$p.value.y < 0.05), ]

result = rbind(colnames(result), result)
write.table(
  result,
  file = outFile,
  sep = "\t",
  quote = F,
  col.names = F,
  row.names = F
)






